title: BORING
description: > # this means to ignore newlines until "baseurl:"
  AWS Blog
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog /creBoring.github.io
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: creator boring # add your name
author-img: siba.jpg # add your photo
about-author: <b>Work hard, Play hard :D</b><br><br>기술 블로그<br><br>Theme by <b>flexible-jekyll</b><br>Font by <b>woowahan</b>,<br> <b>Noto Sans</b> # add description
social-twitter: # add your Twitter handle
social-facebook: dohoon.lee.739 # add your Facebook handle
social-github: creBoring # add your Github handle
social-email: cre.boring@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# kramdown tagging
kramdown:
  auto_ids: true # Auto-generate ID's for headings
