title: Dohun Lee
subtitle: Backend developer
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "https://creboring.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Dohun Lee
author_bio: 안녕하세요, 현재 <b>AWS 파트너사</b>에서 <b>자체 빌링 시스템(CMT)</b> 인프라 구성, 웹 페이지 운영 및 개발을 담당하고 있습니다.<p><b>AWS</b> 내에 인프라를 구축하는 프로젝트에 다수 참여했으며, 컨테이너를 이용한 <b>MSA(Micro Service Architecture)</b> 및 <b>DevOps</b>에 관심이 있습니다.</p>
author_email: "cre.boring@gmail.com"
author_website_url: "creboring.github.io"
author_location: South Korea
typewrite-text: Welcome to my blog, and feel free to ask or advise something :)

# Experiences
author_work_experiences:
            - company_name: 솔트웨어 주식회사
              company_logo: saltware.png
              company_url: https://www.saltware.co.kr
              designation: Software Engineer
              description: <i>Period 2021.07 ~ Current</i><br> - CMT(Cloud Management Tool) Developer<br> - Maintain Company's AWS Infrastructure and CI/CD pipeline<br> - Handling AWS CUR billing data
              visibility: true
            - company_name: 솔트웨어 주식회사
              company_logo: saltware.png
              company_url: https://www.saltware.co.kr
              designation: Technical Support Manager
              description: <i>Period 2017.09 ~ 2021.07</i><br> - AWS Partner Technical Support Manager<br> - AWS Partner Immersionday Instructor
              visibility: true

# Education
author_education_details:
              - college_logo: kpu.png
                college_name: 한국산업기술대학교
                college_url: https://www.kpu.ac.kr
                college_degree: Information Communication Technology Engineering
                description: Bachelor of Technology
                visibility: true
              - college_logo: dsm.png
                college_name: 대덕소프트웨어마이스터고등학교
                college_url: https://dsmhs.djsch.kr
                college_degree: Software Development
                description: Software Meister Highschool
                visibility: true

# Certificates
author_certifications:
  types:
        - type_name: AWS
        - type_name: HRDK
  certificates:
        - certificate_name: Solutions Architect - Associate
          certificate_authenticator: AWS
        - certificate_name: Solutions Architect - Professional
          certificate_authenticator: AWS
        - certificate_name: SysOps Administrator - Associate
          certificate_authenticator: AWS
        - certificate_name: Developer - Associate
          certificate_authenticator: AWS
        - certificate_name: DevOps Engineer - Professional
          certificate_authenticator: AWS
        - certificate_name: Security - Specialty
          certificate_authenticator: AWS
        - certificate_name: 정보처리기사
          certificate_authenticator: HRDK



# social links
github_username:  creBoring
linkedin_username: l22dohun
instagram_username: l22d0hun

#for comments
hyvor_talk_website_id: 5044

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false
show_author_certification_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
