title: Dohun Lee Blog
description: > # this means to ignore newlines until "baseurl:"
  AWS Blog
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog /creBoring.github.io
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dohun Lee # add your name
author-img: siba.jpg # add your photo
about-author: I'm not a dog :D<br><br>This page covers development techniques<br>Theme by __flexible-jekyll__ # add description
social-twitter: # add your Twitter handle
social-facebook: dohoon.lee.739 # add your Facebook handle
social-github: creBoring # add your Github handle
social-email: cre.boring@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
